name: Pull Request
on:
  pull_request:
  branches: [ diffuse ]

jobs:
  # Checkout main branch and build the APK
  build-main:
    runs-on: ubuntu-latest
    steps:
      - name: Read current version
          id: read_property
          uses: christian-draeger/read-properties@1.0.1
          with:
            path: 'app/version.properties'
            property: 'VERSION'
      - name: Current release version is
          run: echo ${{ steps.read_property.outputs.value }}
                 - uses: actions/checkout@v1
      - uses: actions/checkout@v1
        with:
          ref: main
      - name: Build Main APK
        run: |
          ./gradlew assembleDebug
          mv app/build/outputs/apk/release/duckduckgo-{ steps.read_property.outputs.value }-release-unsigned.apk app/build/outputs/apk/debug/app-main.apk
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-main.apk

  # Checkout PR branch and build the APK
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Read current version
        id: read_property
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: 'app/version.properties'
          property: 'VERSION'
      - name: Current release version is
        run: echo ${{ steps.read_property.outputs.value }}
               - uses: actions/checkout@v1
      - name: Build PR APK
          run: |
            ./gradlew assembleDebug
            mv app/build/outputs/apk/debug/duckduckgo-{ steps.read_property.outputs.value }-debug.apk app/build/outputs/apk/debug/app-pr.apk
            - name: Upload APK
              uses: actions/upload-artifact@v1
              with:
                name: apk
                path: app/build/outputs/apk/debug/app-pr.apk

  # Execute Diffuse only when the two APKs are built successfully
  diffuse:
    needs: [build-main, build-pr]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download APKs
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: Execute Diffuse
        run: ./diffuse diff apk/app-master.apk apk/app-pr.apk