name: Pull Request
on:
  pull_request:
  branches: [ diffuse ]

jobs:
  # Checkout PR branch and build the APK
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Build PR APK
          run: ./gradlew assembleDebug
      - name: Upload APK
          uses: actions/upload-artifact@v1
          with:
            name: apk
            path: app/build/outputs/apk/debug/duckduckgo-5.63.1-debug.apk

  # Execute Diffuse only when the two APKs are built successfully
  diffuse:
    needs: [build-pr]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download APKs
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: Execute Diffuse
        run: ./diffuse info app/build/outputs/apk/debug/duckduckgo-5.63.1-debug.apk