name: Pull Request
on:
  pull_request:
  branches: [ diffuse ]

jobs:
  # Checkout main branch and build the APK
  build-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: main
      - name: Build Main APK
        run: |
        ./gradlew assembleDebug
        mv app/build/outputs/apk/debug/duckduckgo-5.63.1-debug.apk app/build/outputs/apk/debug/app-master.apk
      - name: Upload APK
          uses: actions/upload-artifact@v1
          with:
            name: apk
            path: app/build/outputs/apk/debug/app-main.apk

  # Checkout PR branch and build the APK
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Build PR APK
          run: ./gradlew assembleDebug && mv app/build/outputs/apk/debug/duckduckgo-5.63.1-debug.apk app/build/outputs/apk/debug/app-pr.apk
                 - name: Upload APK
                 uses: actions/upload-artifact@v1
                 with:
                   name: apk
                   path: app/build/outputs/apk/debug/app-pr.apk

  # Execute Diffuse only when the two APKs are built successfully
  diffuse:
    needs: [build-main, build-pr]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download APKs
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: Execute Diffuse
        run: ./diffuse diff apk/app-master.apk apk/app-pr.apk